"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DealsTable = void 0;
var DealsTable = /** @class */ (function () {
    function DealsTable() {
    }
    DealsTable.deals = [
        {
            id: 1,
            name: "Deal -- 1",
            type: " Development",
            //startDate: "09/21/20",
            statusId: 2,
            statusName: " PSA",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Eagan West",
            //propertyManager: "Hiram York",
            investmentLead: "Knox Johns",
            bloomlanyLead: "Xander Oliver",
            //images: "./assets/media/propertyImages/15_Dundonald.jpg",
            //properties: "Ap #386-867 Ipsum Av."
        },
        {
            id: 2,
            name: "Deal -- 2",
            type: "Disposition ",
            //startDate: "04/13/21",
            statusId: 1,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Ray Turner",
            //propertyManager: "Kareem Shepard",
            investmentLead: "Travis Workman",
            bloomlanyLead: "Chase Washington",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "5370 Non, Road"
        },
        {
            id: 3,
            name: "Deal -- 3",
            type: " Acquisition ",
            //startDate: "02/03/22",
            statusId: 3,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Harrison Young",
            //propertyManager: "Jackson Richard",
            investmentLead: "Colt Duran",
            bloomlanyLead: "Robert Robbins",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 288, 5643 A, Rd."
        },
        {
            id: 4,
            name: "Deal -- 4",
            type: " Acquisition ",
            //startDate: "04/17/21",
            statusId: 7,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Victor Mathis",
            //propertyManager: "Reed Ruiz",
            investmentLead: "Tyrone Long",
            bloomlanyLead: "Cole Nichols",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "805-3272 Cras St."
        },
        {
            id: 5,
            name: "Deal -- 5",
            type: " Development",
            //startDate: "09/30/20",
            statusId: 5,
            statusName: " PSA",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Zephania Hood",
            //propertyManager: "Drew Knapp",
            investmentLead: "Colton Williamson",
            bloomlanyLead: "Lane Sullivan",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "226-828 Elementum Ave"
        },
        {
            id: 6,
            name: "Deal -- 6",
            type: " Development",
            //startDate: "08/12/21",
            statusId: 2,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Wylie Molina",
            //propertyManager: "Cade Petty",
            investmentLead: "Sawyer Bradford",
            bloomlanyLead: "Lyle Moore",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #839-7397 Vehicula Av."
        },
        {
            id: 7,
            name: "Deal -- 7",
            type: "Disposition ",
            //startDate: "08/12/20",
            statusId: 6,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Chaim Mcneil",
            //propertyManager: "Mark Pena",
            investmentLead: "Moses Kirk",
            bloomlanyLead: "Hop Green",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #839-6301 Facilisis Avenue"
        },
        {
            id: 8,
            name: "Deal -- 8",
            type: " Acquisition ",
            //startDate: "06/10/22",
            statusId: 5,
            statusName: " Letter Of Intent ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Jeremy Peterson",
            //propertyManager: "Palmer Craft",
            investmentLead: "Hamish Wynn",
            bloomlanyLead: "Robert Burris",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "Ap #769-4838 Aliquet Ave"
        },
        {
            id: 9,
            name: "Deal -- 9",
            type: "Disposition ",
            //startDate: "04/30/21",
            statusId: 7,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Herrod Allen",
            //propertyManager: "Burton Morrow",
            investmentLead: "Damian Collier",
            bloomlanyLead: "Yuli Winters",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "P.O. Box 286, 3577 Risus Street"
        },
        {
            id: 10,
            name: "Deal -- 10",
            type: " Acquisition ",
            //startDate: "07/02/22",
            statusId: 2,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Raymond Pruitt",
            //propertyManager: "Uriel Valencia",
            investmentLead: "Abbot Burton",
            bloomlanyLead: "Driscoll Barton",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "Ap #542-1003 Sapien St."
        },
        {
            id: 11,
            name: "Deal -- 11",
            type: " Development",
            //startDate: "04/29/21",
            statusId: 2,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Andrew Gilliam",
            //propertyManager: "Stephen Sanders",
            investmentLead: "Ethan Pace",
            bloomlanyLead: "Griffith Serrano",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "706 Ac Av."
        },
        {
            id: 12,
            name: "Deal -- 12",
            type: " Development",
            //startDate: "02/04/22",
            statusId: 2,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Abdul Stewart",
            //propertyManager: "Kelly Perez",
            investmentLead: "Slade Wells",
            bloomlanyLead: "Alexander Nelson",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "5499 Tempus St."
        },
        {
            id: 13,
            name: "Deal -- 13",
            type: "Disposition ",
            //startDate: "02/19/22",
            statusId: 4,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Brent Riddle",
            //propertyManager: "Harlan Ball",
            investmentLead: "Hiram Knox",
            bloomlanyLead: "Hu Mcgowan",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "Ap #240-4681 Libero Av."
        },
        {
            id: 14,
            name: "Deal -- 14",
            type: "Disposition ",
            //startDate: "06/25/22",
            statusId: 7,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Maxwell Tillman",
            //propertyManager: "Logan David",
            investmentLead: "Kenneth Logan",
            bloomlanyLead: "Kaseem Randall",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "354 Aliquet Rd."
        },
        {
            id: 15,
            name: "Deal -- 15",
            type: "Disposition ",
            //startDate: "12/22/21",
            statusId: 7,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Graham Randolph",
            //propertyManager: "Ian Dawson",
            investmentLead: "Blake Camacho",
            bloomlanyLead: "Conan Joyce",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "7375 Eu St."
        },
        {
            id: 16,
            name: "Deal -- 16",
            type: "Disposition ",
            //startDate: "08/07/21",
            statusId: 3,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Elijah Dunn",
            //propertyManager: "Mark Macdonald",
            investmentLead: "Victor Mayo",
            bloomlanyLead: "Conan Prince",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 538, 259 Urna Av."
        },
        {
            id: 17,
            name: "Deal -- 17",
            type: " Development",
            //startDate: "08/12/20",
            statusId: 7,
            statusName: " PSA",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Clark Stafford",
            //propertyManager: "Zane Schwartz",
            investmentLead: "Cole Humphrey",
            bloomlanyLead: "Berk Burns",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "8107 Augue Avenue"
        },
        {
            id: 18,
            name: "Deal -- 18",
            type: "Disposition ",
            //startDate: "06/17/22",
            statusId: 2,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Lester Boone",
            //propertyManager: "Ralph Oneill",
            investmentLead: "Logan Russell",
            bloomlanyLead: "Merrill Koch",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 417, 8920 Libero Street"
        },
        {
            id: 19,
            name: "Deal -- 19",
            type: "Disposition ",
            //startDate: "07/07/21",
            statusId: 4,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Hamilton Munoz",
            //propertyManager: "August Nixon",
            investmentLead: "Brenden Dyer",
            bloomlanyLead: "Beck Walter",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #418-3158 Risus. Rd."
        },
        {
            id: 20,
            name: "Deal -- 20",
            type: " Acquisition ",
            //startDate: "07/08/22",
            statusId: 3,
            statusName: " PSA",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Carl Rice",
            //propertyManager: "Kirk Garcia",
            investmentLead: "Jonah Robles",
            bloomlanyLead: "Dane Peterson",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "518-8592 Enim Rd."
        },
        {
            id: 21,
            name: "Deal -- 21",
            type: "Disposition ",
            //startDate: "07/03/21",
            statusId: 2,
            statusName: " Waive ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Myles Watkins",
            //propertyManager: "Aquila Baxter",
            investmentLead: "Otto Riddle",
            bloomlanyLead: "Todd Watkins",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 778, 2232 Vel Street"
        },
        {
            id: 22,
            name: "Deal -- 22",
            type: "Disposition ",
            //startDate: "03/25/21",
            statusId: 3,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Darius Kent",
            //propertyManager: "Brendan Hartman",
            investmentLead: "Prescott Preston",
            bloomlanyLead: "Zane Mclean",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #237-3294 Ac Rd."
        },
        {
            id: 23,
            name: "Deal -- 23",
            type: " Development",
            //startDate: "10/25/21",
            statusId: 7,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Rashad Madden",
            //propertyManager: "Chandler Welch",
            investmentLead: "Byron Mejia",
            bloomlanyLead: "Declan Reese",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "Ap #115-8382 Urna Street"
        },
        {
            id: 24,
            name: "Deal -- 24",
            type: "Disposition ",
            //startDate: "07/30/22",
            statusId: 6,
            statusName: "Source Deal ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Micah Porter",
            //propertyManager: "Upton Cross",
            investmentLead: "Justin Oconnor",
            bloomlanyLead: "Wylie Wiggins",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "P.O. Box 367, 7608 Phasellus St."
        },
        {
            id: 25,
            name: "Deal -- 25",
            type: "Disposition ",
            //startDate: "04/11/22",
            statusId: 5,
            statusName: " Take Over",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Bevis Meadows",
            //propertyManager: "Chancellor Carter",
            investmentLead: "Caldwell Hayden",
            bloomlanyLead: "Chaney Bernard",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 604, 2396 Ac, Rd."
        },
        {
            id: 26,
            name: "Deal -- 26",
            type: "Disposition ",
            //startDate: "06/09/22",
            statusId: 2,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Tyler Roach",
            //propertyManager: "Nigel Quinn",
            investmentLead: "Reuben Hinton",
            bloomlanyLead: "Gray Shelton",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "5415 Augue Rd."
        },
        {
            id: 27,
            name: "Deal -- 27",
            type: " Development",
            //startDate: "04/16/22",
            statusId: 7,
            statusName: " Take Over",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Harrison Klein",
            //propertyManager: "Lucas Sexton",
            investmentLead: "Maxwell Barnes",
            bloomlanyLead: "Sawyer Mcfadden",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "9365 Mauris. St."
        },
        {
            id: 28,
            name: "Deal -- 28",
            type: " Acquisition ",
            //startDate: "08/11/21",
            statusId: 6,
            statusName: " PSA",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Phelan Workman",
            //propertyManager: "Caldwell Becker",
            investmentLead: "Zahir Velez",
            bloomlanyLead: "Isaiah Francis",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 148, 8574 Morbi Ave"
        },
        {
            id: 29,
            name: "Deal -- 29",
            type: " Development",
            //startDate: "09/28/20",
            statusId: 7,
            statusName: " Waive ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Colin Rowe",
            //propertyManager: "Carl Middleton",
            investmentLead: "Francis Patel",
            bloomlanyLead: "Tobias Mays",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 268, 408 Et Av."
        },
        {
            id: 30,
            name: "Deal -- 30",
            type: "Disposition ",
            //startDate: "02/12/22",
            statusId: 1,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Garrison Brewer",
            //propertyManager: "Arden Hampton",
            investmentLead: "Grady Beasley",
            bloomlanyLead: "Rogan Bryant",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "976-8523 Suscipit Rd."
        },
        {
            id: 31,
            name: "Deal -- 31",
            type: "Disposition ",
            //startDate: "05/05/22",
            statusId: 4,
            statusName: " PSA",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Ronan Rich",
            //propertyManager: "John Giles",
            investmentLead: "Jin Kidd",
            bloomlanyLead: "Caesar Gray",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 256, 6431 Nullam St."
        },
        {
            id: 32,
            name: "Deal -- 32",
            type: "Disposition ",
            //startDate: "06/13/22",
            statusId: 5,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Ishmael Gamble",
            //propertyManager: "Ferris Stafford",
            investmentLead: "Harrison Holland",
            bloomlanyLead: "Gray Bright",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #745-2120 Feugiat. Road"
        },
        {
            id: 33,
            name: "Deal -- 33",
            type: " Development",
            //startDate: "07/23/21",
            statusId: 5,
            statusName: " Letter Of Intent ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Emery Pitts",
            //propertyManager: "Thane Hayden",
            investmentLead: "Wade Russell",
            bloomlanyLead: "Clarke Lynch",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 676, 320 Nibh. Ave"
        },
        {
            id: 34,
            name: "Deal -- 34",
            type: " Acquisition ",
            //startDate: "10/30/20",
            statusId: 2,
            statusName: " Letter Of Intent ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Bradley Mclaughlin",
            //propertyManager: "Walker Hopkins",
            investmentLead: "Fritz Tate",
            bloomlanyLead: "James Matthews",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "947-1841 Tincidunt Avenue"
        },
        {
            id: 35,
            name: "Deal -- 35",
            type: " Acquisition ",
            //startDate: "06/08/22",
            statusId: 3,
            statusName: "Source Deal ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Trevor Kline",
            //propertyManager: "Hilel Lane",
            investmentLead: "Kibo Mcleod",
            bloomlanyLead: "Orson Craft",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "187-5212 Ac Av."
        },
        {
            id: 36,
            name: "Deal -- 36",
            type: "Disposition ",
            //startDate: "06/20/22",
            statusId: 1,
            statusName: "Source Deal ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Amos Cobb",
            //propertyManager: "Ray Crosby",
            investmentLead: "Graiden Mcdonald",
            bloomlanyLead: "Norman Jensen",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "428-558 Mauris. Avenue"
        },
        {
            id: 37,
            name: "Deal -- 37",
            type: "Disposition ",
            //startDate: "07/07/22",
            statusId: 2,
            statusName: " Take Over",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Thaddeus Lopez",
            //propertyManager: "Kaseem Maddox",
            investmentLead: "Derek Rivers",
            bloomlanyLead: "Baker Strickland",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "P.O. Box 871, 4068 Sit Rd."
        },
        {
            id: 38,
            name: "Deal -- 38",
            type: "Disposition ",
            //startDate: "03/10/21",
            statusId: 6,
            statusName: "Source Deal ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Dolan Randall",
            //propertyManager: "Kane Mejia",
            investmentLead: "Ezra Cervantes",
            bloomlanyLead: "Kenneth Sandoval",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "118-4735 Magna. St."
        },
        {
            id: 39,
            name: "Deal -- 39",
            type: "Disposition ",
            //startDate: "05/15/22",
            statusId: 5,
            statusName: " PSA",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Kieran Robles",
            //propertyManager: "Acton Lyons",
            investmentLead: "Raja Hester",
            bloomlanyLead: "Jelani Farley",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "Ap #841-320 Dolor Rd."
        },
        {
            id: 40,
            name: "Deal -- 40",
            type: " Development",
            //startDate: "06/20/21",
            statusId: 7,
            statusName: " Take Over",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Garth Michael",
            //propertyManager: "Kennedy Garza",
            investmentLead: "Ivor Vazquez",
            bloomlanyLead: "Ferdinand Delgado",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "8756 Nunc Rd."
        },
        {
            id: 41,
            name: "Deal -- 41",
            type: " Development",
            //startDate: "05/21/21",
            statusId: 1,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Chester Deleon",
            //propertyManager: "Holmes Hopkins",
            investmentLead: "Robert Leach",
            bloomlanyLead: "Oscar Nguyen",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 700, 2279 Risus Street"
        },
        {
            id: 42,
            name: "Deal -- 42",
            type: " Development",
            //startDate: "05/27/22",
            statusId: 3,
            statusName: " Letter Of Intent ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Rajah Lindsey",
            //propertyManager: "Lucas Conrad",
            investmentLead: "Bruce Rowland",
            bloomlanyLead: "Carl Cameron",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "7430 Suspendisse Ave"
        },
        {
            id: 43,
            name: "Deal -- 43",
            type: "Disposition ",
            //startDate: "07/14/21",
            statusId: 2,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "James Osborn",
            //propertyManager: "Garrett Nieves",
            investmentLead: "Aristotle Lee",
            bloomlanyLead: "Hayden Rowland",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "910-9272 Turpis. Avenue"
        },
        {
            id: 44,
            name: "Deal -- 44",
            type: " Acquisition ",
            //startDate: "05/14/21",
            statusId: 1,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Clinton Lara",
            //propertyManager: "Uriah Johnson",
            investmentLead: "Stewart Berg",
            bloomlanyLead: "Orlando Nicholson",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #388-619 Ac Street"
        },
        {
            id: 45,
            name: "Deal -- 45",
            type: "Disposition ",
            //startDate: "03/15/21",
            statusId: 2,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Nash Page",
            //propertyManager: "Blake Hickman",
            investmentLead: "Cooper Salas",
            bloomlanyLead: "Vance Reynolds",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "505-4451 Morbi Rd."
        },
        {
            id: 46,
            name: "Deal -- 46",
            type: " Acquisition ",
            //startDate: "06/15/22",
            statusId: 4,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Lester Rowe",
            //propertyManager: "Kasimir Roberson",
            investmentLead: "Warren Witt",
            bloomlanyLead: "Tate Fitzgerald",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "616-3196 Condimentum Street"
        },
        {
            id: 47,
            name: "Deal -- 47",
            type: " Development",
            //startDate: "02/19/21",
            statusId: 3,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Anthony Travis",
            //propertyManager: "Wayne Mccullough",
            investmentLead: "Keaton Serrano",
            bloomlanyLead: "Price Little",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 359, 7190 Senectus Avenue"
        },
        {
            id: 48,
            name: "Deal -- 48",
            type: " Acquisition ",
            //startDate: "05/26/21",
            statusId: 3,
            statusName: " Due Diligence ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Tobias Velazquez",
            //propertyManager: "Cedric Hughes",
            investmentLead: "Oleg Schmidt",
            bloomlanyLead: "Curran Chavez",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "P.O. Box 353, 6226 Libero St."
        },
        {
            id: 49,
            name: "Deal -- 49",
            type: " Acquisition ",
            //startDate: "04/15/21",
            statusId: 1,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Brody Lynch",
            //propertyManager: "Harding Watson",
            investmentLead: "Cooper Hodge",
            bloomlanyLead: "Clinton Patterson",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #856-4846 Eget Street"
        },
        {
            id: 50,
            name: "Deal -- 50",
            type: " Acquisition ",
            //startDate: "07/17/21",
            statusId: 4,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Kermit Garner",
            //propertyManager: "Trevor Sanders",
            investmentLead: "Gannon Powers",
            bloomlanyLead: "Caleb Mcdonald",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "577-5028 Scelerisque St."
        },
        {
            id: 51,
            name: "Deal -- 51",
            type: " Development",
            //startDate: "11/09/20",
            statusId: 3,
            statusName: " Take Over",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Dale Bush",
            //propertyManager: "Josiah Wilkins",
            investmentLead: "Octavius Gates",
            bloomlanyLead: "Cadman Clayton",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #336-5281 Nisi. St."
        },
        {
            id: 52,
            name: "Deal -- 52",
            type: " Acquisition ",
            //startDate: "05/03/21",
            statusId: 6,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Jason Davis",
            //propertyManager: "Lewis Cotton",
            investmentLead: "Malachi Hernandez",
            bloomlanyLead: "Hedley Medina",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #465-1509 Donec Av."
        },
        {
            id: 53,
            name: "Deal -- 53",
            type: "Disposition ",
            //startDate: "06/12/21",
            statusId: 1,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Grant Young",
            //propertyManager: "Jason Burt",
            investmentLead: "Andrew Pearson",
            bloomlanyLead: "Amir Kirkland",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "4778 Neque. Street"
        },
        {
            id: 54,
            name: "Deal -- 54",
            type: " Development",
            //startDate: "04/19/21",
            statusId: 2,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Yoshio Larson",
            //propertyManager: "Maxwell Vasquez",
            investmentLead: "Vaughan Price",
            bloomlanyLead: "Macon Lucas",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 440, 3993 Eleifend Road"
        },
        {
            id: 55,
            name: "Deal -- 55",
            type: " Acquisition ",
            //startDate: "04/13/22",
            statusId: 3,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Elmo Ruiz",
            //propertyManager: "Simon Clark",
            investmentLead: "Harlan Jones",
            bloomlanyLead: "Demetrius Riddle",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "8557 Ipsum Ave"
        },
        {
            id: 56,
            name: "Deal -- 56",
            type: " Development",
            //startDate: "10/09/20",
            statusId: 5,
            statusName: " PSA",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Otto Cameron",
            //propertyManager: "Philip Buckley",
            investmentLead: "Samson Green",
            bloomlanyLead: "Jermaine Tanner",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "9702 Vel Rd."
        },
        {
            id: 57,
            name: "Deal -- 57",
            type: " Acquisition ",
            //startDate: "06/03/21",
            statusId: 3,
            statusName: "Source Deal ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Martin Mclaughlin",
            //propertyManager: "Brett Waller",
            investmentLead: "Keane Adkins",
            bloomlanyLead: "Davis Waters",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "879-3104 Neque Road"
        },
        {
            id: 58,
            name: "Deal -- 58",
            type: "Disposition ",
            //startDate: "06/23/22",
            statusId: 4,
            statusName: " Due Diligence ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Ethan Byers",
            //propertyManager: "Basil Pearson",
            investmentLead: "Zane Knapp",
            bloomlanyLead: "Ethan Allison",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #210-5298 Nulla. Rd."
        },
        {
            id: 59,
            name: "Deal -- 59",
            type: " Development",
            //startDate: "03/06/21",
            statusId: 4,
            statusName: " Letter Of Intent ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Nash Raymond",
            //propertyManager: "Omar Rodriguez",
            investmentLead: "Cody Jennings",
            bloomlanyLead: "David Castro",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "1694 Purus, Street"
        },
        {
            id: 60,
            name: "Deal -- 60",
            type: " Acquisition ",
            //startDate: "01/21/22",
            statusId: 4,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Uriel Russo",
            //propertyManager: "Garrison Walter",
            investmentLead: "Carl Aguilar",
            bloomlanyLead: "Berk Small",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "9191 Suspendisse Avenue"
        },
        {
            id: 61,
            name: "Deal -- 61",
            type: " Development",
            //startDate: "08/02/22",
            statusId: 4,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Flynn Mcneil",
            //propertyManager: "Carlos Christensen",
            investmentLead: "Brenden Bell",
            bloomlanyLead: "Ahmed Caldwell",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "485-2760 Phasellus St."
        },
        {
            id: 62,
            name: "Deal -- 62",
            type: " Acquisition ",
            //startDate: "09/06/20",
            statusId: 3,
            statusName: " PSA",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Raphael Allison",
            //propertyManager: "August Burke",
            investmentLead: "Gregory Gomez",
            bloomlanyLead: "Sean Welch",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "1730 Erat. Ave"
        },
        {
            id: 63,
            name: "Deal -- 63",
            type: "Disposition ",
            //startDate: "08/20/21",
            statusId: 5,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Jerome Zamora",
            //propertyManager: "Gage Jacobson",
            investmentLead: "Boris Harvey",
            bloomlanyLead: "Dante Henson",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "422 Dolor Street"
        },
        {
            id: 64,
            name: "Deal -- 64",
            type: " Acquisition ",
            //startDate: "04/26/21",
            statusId: 6,
            statusName: "Source Deal ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Hayes Warren",
            //propertyManager: "Dean Ross",
            investmentLead: "Oren Bright",
            bloomlanyLead: "Hashim Conley",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "984-9489 Varius St."
        },
        {
            id: 65,
            name: "Deal -- 65",
            type: " Acquisition ",
            //startDate: "11/12/20",
            statusId: 5,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Fritz Mccormick",
            //propertyManager: "Timothy Mays",
            investmentLead: "Stone Hewitt",
            bloomlanyLead: "Quentin Rogers",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 618, 2715 Velit Rd."
        },
        {
            id: 66,
            name: "Deal -- 66",
            type: " Development",
            //startDate: "04/03/21",
            statusId: 5,
            statusName: " Take Over",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Scott Bradshaw",
            //propertyManager: "Boris Vega",
            investmentLead: "Rudyard Juarez",
            bloomlanyLead: "Vaughan Bailey",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "875-3768 Cursus Avenue"
        },
        {
            id: 67,
            name: "Deal -- 67",
            type: " Acquisition ",
            //startDate: "05/21/21",
            statusId: 1,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Scott Ayers",
            //propertyManager: "Ashton Frederick",
            investmentLead: "Hayden Blair",
            bloomlanyLead: "Colin Murray",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 379, 7462 Eu, Avenue"
        },
        {
            id: 68,
            name: "Deal -- 68",
            type: "Disposition ",
            //startDate: "08/30/21",
            statusId: 5,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Caldwell Beasley",
            //propertyManager: "Cole Gentry",
            investmentLead: "Jason Shepherd",
            bloomlanyLead: "Baker Merrill",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "1314 Litora Avenue"
        },
        {
            id: 69,
            name: "Deal -- 69",
            type: " Acquisition ",
            //startDate: "04/21/22",
            statusId: 7,
            statusName: " Letter Of Intent ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Hamilton Clayton",
            //propertyManager: "Armando Larson",
            investmentLead: "Demetrius Combs",
            bloomlanyLead: "Lucian Paul",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "Ap #515-2392 Ornare Rd."
        },
        {
            id: 70,
            name: "Deal -- 70",
            type: " Acquisition ",
            //startDate: "04/29/22",
            statusId: 4,
            statusName: " Letter Of Intent ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Julian Vaughn",
            //propertyManager: "Holmes Robinson",
            investmentLead: "Patrick Sexton",
            bloomlanyLead: "Barry Freeman",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "Ap #415-5415 Eget, Street"
        },
        {
            id: 71,
            name: "Deal -- 71",
            type: "Disposition ",
            //startDate: "08/22/20",
            statusId: 5,
            statusName: " Letter Of Intent ",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Upton Lyons",
            //propertyManager: "Hakeem Chan",
            investmentLead: "Rigel Wilkinson",
            bloomlanyLead: "Hayden Mcfadden",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 434, 3511 Vel, Rd."
        },
        {
            id: 72,
            name: "Deal -- 72",
            type: "Disposition ",
            //startDate: "11/21/21",
            statusId: 6,
            statusName: "Source Deal ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Kenneth Clay",
            //propertyManager: "Macaulay Frye",
            investmentLead: "Ulric Odom",
            bloomlanyLead: "Damon Torres",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "Ap #765-8582 Nullam Ave"
        },
        {
            id: 73,
            name: "Deal -- 73",
            type: " Development",
            //startDate: "04/15/21",
            statusId: 5,
            statusName: "Source Deal ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Colt Hatfield",
            //propertyManager: "Evan Logan",
            investmentLead: "Elvis Blevins",
            bloomlanyLead: "Colorado Matthews",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "Ap #459-6117 Accumsan St."
        },
        {
            id: 74,
            name: "Deal -- 74",
            type: "Disposition ",
            //startDate: "08/21/20",
            statusId: 3,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Magee Hartman",
            //propertyManager: "Joel Love",
            investmentLead: "Burke Sloan",
            bloomlanyLead: "Elijah Roberson",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 146, 1661 Cum Rd."
        },
        {
            id: 75,
            name: "Deal -- 75",
            type: " Acquisition ",
            //startDate: "03/09/21",
            statusId: 1,
            statusName: "Source Deal ",
            businessUnitId: 1,
            businessUnitName: "IMH ",
            //assetManager: "Austin Anthony",
            //propertyManager: "Daniel Maynard",
            investmentLead: "Price Hoffman",
            bloomlanyLead: "Quamar Mooney",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "Ap #100-9332 Metus Street"
        },
        {
            id: 76,
            name: "Deal -- 76",
            type: "Disposition ",
            //startDate: "01/31/22",
            statusId: 4,
            statusName: " PSA",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Fulton Conrad",
            //propertyManager: "Bevis Lester",
            investmentLead: "Gannon Gilmore",
            bloomlanyLead: "Marsden Greer",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 944, 7150 Integer Av."
        },
        {
            id: 77,
            name: "Deal -- 77",
            type: "Disposition ",
            //startDate: "05/12/22",
            statusId: 7,
            statusName: " PSA",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Joel Pierce",
            //propertyManager: "Driscoll Mcbride",
            investmentLead: "Price Oneal",
            bloomlanyLead: "Evan Townsend",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #629-9675 Malesuada Avenue"
        },
        {
            id: 78,
            name: "Deal -- 78",
            type: "Disposition ",
            //startDate: "02/28/22",
            statusId: 1,
            statusName: " Letter Of Intent ",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Quentin Mosley",
            //propertyManager: "Neil Blackburn",
            investmentLead: "Tiger Green",
            bloomlanyLead: "Charles Lewis",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 511, 1389 Velit St."
        },
        {
            id: 79,
            name: "Deal -- 79",
            type: " Development",
            //startDate: "08/10/21",
            statusId: 1,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Demetrius Gillespie",
            //propertyManager: "Ronan Shaw",
            investmentLead: "Buckminster Yates",
            bloomlanyLead: "Fitzgerald Collins",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 532, 135 Duis Avenue"
        },
        {
            id: 80,
            name: "Deal -- 80",
            type: "Disposition ",
            //startDate: "05/21/21",
            statusId: 5,
            statusName: " Closing ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Phelan Lindsay",
            //propertyManager: "August Mendoza",
            investmentLead: "Kaseem Cantu",
            bloomlanyLead: "Nehru Shepherd",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "5164 Blandit Street"
        },
        {
            id: 81,
            name: "Deal -- 81",
            type: " Acquisition ",
            //startDate: "12/16/21",
            statusId: 7,
            statusName: " Letter Of Intent ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Igor Guy",
            //propertyManager: "Gregory Benton",
            investmentLead: "George Shepard",
            bloomlanyLead: "Colin Gaines",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "2139 Egestas, Av."
        },
        {
            id: 82,
            name: "Deal -- 82",
            type: " Acquisition ",
            //startDate: "01/09/22",
            statusId: 6,
            statusName: " Take Over",
            businessUnitId: 3,
            businessUnitName: "IMH ",
            //assetManager: "Garrett Cooke",
            //propertyManager: "Nehru Duran",
            investmentLead: "Barry Dickson",
            bloomlanyLead: "Oleg Ortiz",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 913, 5500 In Ave"
        },
        {
            id: 83,
            name: "Deal -- 83",
            type: " Development",
            //startDate: "11/20/20",
            statusId: 6,
            statusName: " Waive ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Jerry Thomas",
            //propertyManager: "Raja Harvey",
            investmentLead: "Cairo Sandoval",
            bloomlanyLead: "Garrison Terrell",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "5904 Est, Av."
        },
        {
            id: 84,
            name: "Deal -- 84",
            type: " Development",
            //startDate: "10/05/21",
            statusId: 3,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Amal Jones",
            //propertyManager: "Griffith Griffin",
            investmentLead: "Jacob Matthews",
            bloomlanyLead: "Hakeem Pugh",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "P.O. Box 651, 5902 Nullam Avenue"
        },
        {
            id: 85,
            name: "Deal -- 85",
            type: " Development",
            //startDate: "11/16/21",
            statusId: 5,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: " Private ",
            //assetManager: "Silas Smith",
            //propertyManager: "Rudyard Lopez",
            investmentLead: "Gabriel Alford",
            bloomlanyLead: "Addison Gonzales",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #617-5506 Urna Road"
        },
        {
            id: 86,
            name: "Deal -- 86",
            type: " Acquisition ",
            //startDate: "01/15/21",
            statusId: 7,
            statusName: " Letter Of Intent ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Brent Barton",
            //propertyManager: "Boris Mosley",
            investmentLead: "Abbot Arnold",
            bloomlanyLead: "Marvin Mcdaniel",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "614-2613 Scelerisque St."
        },
        {
            id: 87,
            name: "Deal -- 87",
            type: "Disposition ",
            //startDate: "09/25/21",
            statusId: 3,
            statusName: " Waive ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Walter Burke",
            //propertyManager: "Daquan Fitzpatrick",
            investmentLead: "Marvin Gilmore",
            bloomlanyLead: "Noah Pickett",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "902-9620 Nullam Road"
        },
        {
            id: 88,
            name: "Deal -- 88",
            type: "Disposition ",
            //startDate: "05/27/22",
            statusId: 2,
            statusName: " PSA",
            businessUnitId: 1,
            businessUnitName: " Private ",
            //assetManager: "Brody Oneal",
            //propertyManager: "Beau Steele",
            investmentLead: "Hunter Serrano",
            bloomlanyLead: "Yuli Gray",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "972 Nunc St."
        },
        {
            id: 89,
            name: "Deal -- 89",
            type: " Acquisition ",
            //startDate: "08/31/21",
            statusId: 1,
            statusName: " Closing ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Shad Johnson",
            //propertyManager: "Graham Carter",
            investmentLead: "Marsden Washington",
            bloomlanyLead: "Dolan Rosario",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #693-7554 Facilisis St."
        },
        {
            id: 90,
            name: "Deal -- 90",
            type: "Disposition ",
            //startDate: "03/03/21",
            statusId: 7,
            statusName: " Take Over",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Declan Decker",
            //propertyManager: "Evan Campbell",
            investmentLead: "Tad Gregory",
            bloomlanyLead: "Allen Haley",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "3402 Non, St."
        },
        {
            id: 91,
            name: "Deal -- 91",
            type: " Acquisition ",
            //startDate: "02/27/22",
            statusId: 7,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Buckminster Arnold",
            //propertyManager: "James Mckenzie",
            investmentLead: "Blaze Harper",
            bloomlanyLead: "Upton Mays",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "P.O. Box 678, 2112 Magna Rd."
        },
        {
            id: 92,
            name: "Deal -- 92",
            type: "Disposition ",
            //startDate: "03/23/22",
            statusId: 6,
            statusName: " Due Diligence ",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Magee Berg",
            //propertyManager: "Christopher Fry",
            investmentLead: "Perry Foley",
            bloomlanyLead: "Solomon Preston",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #782-2710 Quisque Av."
        },
        {
            id: 93,
            name: "Deal -- 93",
            type: " Development",
            //startDate: "07/04/21",
            statusId: 4,
            statusName: " Closing ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Grant Newton",
            //propertyManager: "Guy Slater",
            investmentLead: "Calvin Boyle",
            bloomlanyLead: "Gannon Gray",
            //images: " ./assets/media/propertyImages/15_Dundonald.jpg ",
            //properties: "7583 Neque Road"
        },
        {
            id: 94,
            name: "Deal -- 94",
            type: " Development",
            //startDate: "04/14/22",
            statusId: 4,
            statusName: " PSA",
            businessUnitId: 1,
            businessUnitName: " Blackstar",
            //assetManager: "Addison Rose",
            //propertyManager: "Vance Chan",
            investmentLead: "Colorado Rowe",
            bloomlanyLead: "Amos Kirk",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "8260 Nunc St."
        },
        {
            id: 95,
            name: "Deal -- 95",
            type: "Disposition ",
            //startDate: "10/28/21",
            statusId: 1,
            statusName: " Letter Of Intent ",
            businessUnitId: 2,
            businessUnitName: " Blackstar",
            //assetManager: "Dillon Alford",
            //propertyManager: "Samson Sanford",
            investmentLead: "Paul Hess",
            bloomlanyLead: "Caldwell Curry",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 965, 7671 Mi Avenue"
        },
        {
            id: 96,
            name: "Deal -- 96",
            type: " Development",
            //startDate: "11/27/21",
            statusId: 3,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Simon Henderson",
            //propertyManager: "Marvin Washington",
            investmentLead: "Derek Ray",
            bloomlanyLead: "Jesse Mercado",
            //images: "./assets/media/propertyImages/67 Parkwoods-2.jpg ",
            //properties: "200-1977 Felis. Road"
        },
        {
            id: 97,
            name: "Deal -- 97",
            type: "Disposition ",
            //startDate: "08/02/21",
            statusId: 5,
            statusName: " Due Diligence ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Wylie Shelton",
            //propertyManager: "Arsenio Aguirre",
            investmentLead: "Cullen Garrison",
            bloomlanyLead: "Jeremy Shepard",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "Ap #155-3976 Aenean Avenue"
        },
        {
            id: 98,
            name: "Deal -- 98",
            type: "Disposition ",
            //startDate: "04/06/21",
            statusId: 4,
            statusName: " Waive ",
            businessUnitId: 2,
            businessUnitName: "IMH ",
            //assetManager: "Dalton Bennett",
            //propertyManager: "Coby Ryan",
            investmentLead: "Garrett Mckinney",
            bloomlanyLead: "Keane Norman",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "2085 Ut Street"
        },
        {
            id: 99,
            name: "Deal -- 99",
            type: " Development",
            //startDate: "06/11/22",
            statusId: 5,
            statusName: " Closing ",
            businessUnitId: 3,
            businessUnitName: " Private ",
            //assetManager: "Seth Emerson",
            //propertyManager: "Armando Kirkland",
            investmentLead: "Erasmus Hardy",
            bloomlanyLead: "Dominic Wallace",
            //images: " ./assets/media/propertyImages/50BurnHill.jpg ",
            //properties: "P.O. Box 731, 3972 Vivamus Ave"
        },
        {
            id: 100,
            name: "Deal -- 100",
            type: " Acquisition ",
            //startDate: "11/08/21",
            statusId: 3,
            statusName: " Due Diligence ",
            businessUnitId: 3,
            businessUnitName: " Blackstar",
            //assetManager: "Quinn Aguirre",
            //propertyManager: "Dean Montgomery",
            investmentLead: "Ignatius Espinoza",
            bloomlanyLead: "Nasim Sharp",
            //images: " ./assets/media/propertyImages/49 McMurchy.jpg ",
            //properties: "P.O. Box 570, 2702 Blandit Rd."
        }
    ];
    return DealsTable;
}());
exports.DealsTable = DealsTable;
//# sourceMappingURL=deals.table.js.map